#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process.
#Getting pid from /4-to_infinity_and_beyond process.
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)
if [ -n "$id" ]
then
  kill -15 "$id"
fi
