#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but in 9th iteration display Best School the Hi
a=1

while [ $a -le 10 ]
do
    echo "Best School"
    if [ $a -eq 9 ]
    then
        echo "Hi"
    fi
    a=$(( a + 1 ))
done
